### ISSUE TITLE
Node 11 compatibility

### ISSUE THREAD

**Issue by vincent-ogury** [felixge/node-graphite#14]
Hi,

I've got this when I use node 11.
```
error graphite@0.1.3: The engine "node" is incompatible with this module. Expected version ">=4 <10". Got "11.0.0"
```
Any reason to block node 11?

thanks

**Comment by vincent-ogury** [comment]
Same for node 10.

Strange thing is that you add test on node 10, but disable installation for this version ...
I have test against node 11, it works.

**Comment by Serphentas** [comment]
Hi,

Actually no specific reason, it's just that in the [last PR](https://github.com/felixge/node-graphite/pull/12) this changed.

Could you please open a PR for this ?

Thanks.

**Comment by Serphentas** [comment]
See #15
