### ISSUE TITLE
Graphite client unable to reconnect after server connection is closed

### ISSUE THREAD

**Issue by jonathansamines** [felixge/node-graphite#16]
Hello, reporting an issue here:

**Context**
 As of Node 15.0.0, the client is unable to reconnect on abrupt terminations by the graphite server. Once the server connection is terminated, calls to `client.write()` always fail with:

```bash
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:487:14)
    at LazySocket.write (/opt/xoom/apps/smt/node_modules/lazy-socket/lib/LazySocket.js:39:24)
    at CarbonClient.write (/opt/xoom/apps/smt/node_modules/graphite/lib/CarbonClient.js:21:16)
    at GraphiteClient.write (/opt/xoom/apps/smt/node_modules/graphite/lib/GraphiteClient.js:71:16)
```

**Problem**
The problems seems to reside in `node-lazy-socket`, which is broken on Node 15 or above (See https://github.com/felixge/node-lazy-socket/issues/3)

**Suggested solution**
We would ideally solve the problem on `node-lazy-socket`, but not sure any pull request is likely to be merged as it was last released 10 years ago. So I am thinking we could vendor it within this module and fix the problem here. Thoughts?

**Comment by Serphentas** [comment]
Hello,

Thanks for reporting this problem. I personally only have rights on this repo and not https://github.com/felixge/node-lazy-socket, so unless @felixge can step in, it would be any one of these two options:
- packaging the needed fixed code in the module,
- creating a new repo just for `node-lazy-socket` features.

What do you think ?

**Comment by jonathansamines** [comment]
Thanks for a prompt response @Serphentas. I checked `lazy-sockets` [dependents](https://www.npmjs.com/browse/depended/lazy-socket) and doesn't look like there are too many libraries relying on it. Packing the fixed code as part of `graphite` seems like a reasonable option.

Will work on this and try to create a pull request shortly.

**Comment by jonathansamines** [comment]
@Serphentas Pull request created at https://github.com/felixge/node-graphite/issues/16. Let me know of any questions.
